services:
  app:
    build: .
    image: schedule_api:0.9
    container_name: schedule_api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /home/dtraitor/schedule_configs/appsettings.json:/app/configs/appsettings.json:ro
    depends_on:
      - db
    networks:
      - schedule-net

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - schedule-net

volumes:
  postgres_data:

networks:
  schedule-net:
    external: true
